# NUMPY
Numpy is a library which allows us to work with arrays. Numpy arrays are set of values which are all the same type. Though numpy arrays are similar to lists, the fact that they contain values of same type makes it much faster.

Numpy is an important milestone in this course. We will see in the following section the Pandas library which is the heart of Data Science with Python is based on the numpy library.

Let's start exploring numpy!

To install the numpy module, run the lines below in the command line.

## Anaconda distribution:
    conda install numpy
## Python-pip:
    pip install numpy

#### First we need to import the numpy module, which can be assigned to a short name of np(often used for numpy)

In [1]:
import numpy as np

### Creating an array from a list

In [2]:
list1 = [0,1,2,3]
list1

[0, 1, 2, 3]

In [3]:
array1 = np.array(list1)
array1

array([0, 1, 2, 3])

In [4]:
list2 = [10,11,12,13]
list2

[10, 11, 12, 13]

In [5]:
comb_list = [list1,list2]
comb_list

[[0, 1, 2, 3], [10, 11, 12, 13]]

In [6]:
comb_array = np.array(comb_list)
comb_array

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [7]:
comb_array.dtype

dtype('int32')

In [8]:
# dtypes --> float, int, unint, str, void

In [9]:
np.array(comb_list,dtype='float')

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]])

### Creating specific arrays using the functions of the numpy library

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
zeros_array = np.zeros((5,2))
zeros_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
zeros_array.dtype

dtype('float64')

In [13]:
zeros_array.astype('int')  # we can assign a different data type 

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.empty((3,4))

array([[1.013e-321, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000]])

In [16]:
np.eye(5)  #creates a matrix of size 5x5 with ones on diagonal 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.arange(5)  #creates an array starting from 0 until 5

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,10,2)   #  starting from 5 until 10 with every second value


array([5, 7, 9])

In [19]:
np.linspace(0,5,11) # starting from 0 to 5 with 11 evenly spaced numbers

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

### creating arrays with random


In [20]:
import numpy.random as rd

In [21]:
rd.rand(10) # creates an array with 10 random floating numbers

array([0.18708262, 0.63881831, 0.92129968, 0.94168787, 0.74330099,
       0.85163447, 0.46062922, 0.23682206, 0.94311494, 0.67499269])

In [22]:
rd.randint(2,5,10) # an array with 10 integer numbers which are randomly chosen between 0-5

array([2, 3, 2, 3, 2, 2, 2, 2, 2, 3])

In [23]:
rd.randn(10)   # random 10 numbers with a normal distribution

array([ 0.99145578, -0.31552565, -1.3466226 , -1.10818929, -1.27105234,
        0.98999295, -0.03552595,  1.03563375, -0.09534563,  0.79845292])

In [24]:
array = np.random.randint(0,10,10)
array

array([5, 7, 3, 9, 1, 6, 0, 6, 7, 3])

In [25]:
array = array.reshape(5,2) #change the shape of the array
array

array([[5, 7],
       [3, 9],
       [1, 6],
       [0, 6],
       [7, 3]])