### Arithmetical operations with numpy arrays
#### Let's import the random module from numpy as rd

In [1]:

import numpy.random as rd

In [2]:
array = rd.randint(1,5,10)
array

array([2, 4, 4, 1, 1, 1, 1, 1, 4, 1])

In [3]:
array = array.reshape(5,2)
array

array([[2, 4],
       [4, 1],
       [1, 1],
       [1, 1],
       [4, 1]])

## Add

In [4]:
array + array 

array([[4, 8],
       [8, 2],
       [2, 2],
       [2, 2],
       [8, 2]])

## Substract

In [5]:
array - array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

## Multiply

In [6]:
array * array

array([[ 4, 16],
       [16,  1],
       [ 1,  1],
       [ 1,  1],
       [16,  1]])

In [7]:
array*10

array([[20, 40],
       [40, 10],
       [10, 10],
       [10, 10],
       [40, 10]])

## Divide

In [8]:
1/array 

array([[0.5 , 0.25],
       [0.25, 1.  ],
       [1.  , 1.  ],
       [1.  , 1.  ],
       [0.25, 1.  ]])

In [9]:
1//array 

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1]])

## Exponent

In [10]:
array**2

array([[ 4, 16],
       [16,  1],
       [ 1,  1],
       [ 1,  1],
       [16,  1]])