# Built-in functions
Numpy library has some very useful functions already built into the library.

Let's have a look at some important ones.

In [1]:
import numpy as np

Creating an array to play on:

In [2]:
array = np.arange(15).reshape(5,3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Sum of all elements of an array

In [3]:
array.sum()          # adds all items of the array

105

### Sum along the row

In [4]:
array.sum(axis=0)    # adds the items along the row (first axis = rows)

array([30, 35, 40])

### Sum along the column

In [5]:
array.sum(axis=1)    # adds the items along the column (second axis = columns)

array([ 3, 12, 21, 30, 39])

### Get max and min

In [6]:
array.max()          # finds the maximum value in the array

14

In [7]:
array.max(axis=0)    # finds the maximum value on the first axis

array([12, 13, 14])

In [8]:
array.argmax(axis=1) # index of the maximum value on the second axis

array([2, 2, 2, 2, 2], dtype=int64)

In [9]:
array.min(axis=1)    # minimum value on second axis

array([ 0,  3,  6,  9, 12])

### Some statistical functions

In [10]:
array.var()          # variance

18.666666666666668

In [11]:
array.std()          # standard deviation

4.320493798938574

In [12]:
array.mean(axis=1)   # average along second axis (columns)

array([ 1.,  4.,  7., 10., 13.])

### Sort

let's create a random array to play on:

In [13]:
import numpy.random as rd

In [14]:
sort_array = rd.randn(12).reshape(4,3)
sort_array

array([[-0.88196828, -0.50464171, -1.0919981 ],
       [ 0.63609246,  0.72652299, -0.20538062],
       [-0.38081513,  0.77757898, -0.13349486],
       [ 1.16287297,  1.24685044,  0.20443283]])

In [15]:
sort_array.sort(axis=0)
sort_array

array([[-0.88196828, -0.50464171, -1.0919981 ],
       [-0.38081513,  0.72652299, -0.20538062],
       [ 0.63609246,  0.77757898, -0.13349486],
       [ 1.16287297,  1.24685044,  0.20443283]])

In [16]:
sort_array.sort(axis=1)
sort_array

array([[-1.0919981 , -0.88196828, -0.50464171],
       [-0.38081513, -0.20538062,  0.72652299],
       [-0.13349486,  0.63609246,  0.77757898],
       [ 0.20443283,  1.16287297,  1.24685044]])

We can also sort arrays containing strings:

In [17]:
cities = np.array(['Chicago','Sydney','Canberra','Izmir',
                  'Istanbul','Bochum','Stuttgart'])
cities

array(['Chicago', 'Sydney', 'Canberra', 'Izmir', 'Istanbul', 'Bochum',
       'Stuttgart'], dtype='<U9')

In [18]:
cities.sort()
cities

array(['Bochum', 'Canberra', 'Chicago', 'Istanbul', 'Izmir', 'Stuttgart',
       'Sydney'], dtype='<U9')

find unique items of an array (similar like in lists):

In [19]:
np.unique(cities)      # multiple items are only taken once

array(['Bochum', 'Canberra', 'Chicago', 'Istanbul', 'Izmir', 'Stuttgart',
       'Sydney'], dtype='<U9')

looking for an item in the array:

In [20]:
np.in1d(['Stuttgart','Miami'],cities)  #returns boolean

array([ True, False])

## Size of an array

In [21]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Dimensions of the array:

In [22]:
array.shape

(5, 3)

number of rows:

In [23]:
array.shape[0]    

5

number of columns:

In [24]:
array.shape[1]  

3

Total size, total number of items in the array (row x column):

In [25]:
array.size      

15

## Boolean arrays

In [26]:
bool_array = np.array([True,True,False,False])
bool_array

array([ True,  True, False, False])

In [27]:
bool_array.any()

True

In [28]:
bool_array.all()

False