# Numpy exercises

Some numpy exercises about what we have learned so far.

#### 1) import numpy library as np:

#### 2) Convert the given list to a numpy array:
        lst = [1,2,3]


In [2]:
lst = [1,2,3]

array([1, 2, 3])

#### 3) Create an array with five 1's:

array([1., 1., 1., 1., 1.])

#### 4) Create an array of size 2x3 with 1's (2 rows, 3 columns) and assign it to a variable:

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 4a) Using the variable you have created, change the data type of the array to int:

array([[1, 1, 1],
       [1, 1, 1]])

#### 5) Create an array of size 3x3 with 4's on the diagonal:

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

#### 6) Create an array from 0 upto 10 (10 not included):

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 6a) Create an array in range from 12 to 26 using every second number:

array([12, 14, 16, 18, 20, 22, 24])

#### 7) create an array between 2 and 4 with 8 equal spaces:

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

#### 8) import random module from numpy as rd

#### 9) Create a random array of 5 elements:

#### 10) Create a random array of size 3x5 with values between 0-10:

#### 11) take square of the array we have just created in no. 10:

#### 12) using given array:
       array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
####  Create a copy of the array using the last three values of the given array. 
#### Then change the first value of the array with 99.

In [15]:
arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
#Create a copy of the array using the last three values of the given array.

In [17]:
#change the first value of the array with 99.

array([99, 12, 13])

#### 13) Create the below arr_2D array using the arange() function: 

        arr_2D = array([[ 0,  1,  2,  3,  4],
                       [ 5,  6,  7,  8,  9],
                       [10, 11, 12, 13, 14],
                       [15, 16, 17, 18, 19],
                       [20, 21, 22, 23, 24]])
               
#### Get the array below using indexing:
                 array([[ 7,  8,  9],
                       [12, 13, 14]])


In [18]:
#create the array 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
#get the array shown using indexing

array([[ 7,  8,  9],
       [12, 13, 14]])

## Well done!